import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav.";
import { motion } from "framer-motion";
import Grid from "@mui/material/Grid";
import Item from "@mui/material/Box";
import Backdrop from "@mui/material/Backdrop";
import Box from "@mui/material/Box";
import Modal from "@mui/material/Modal";
import Fade from "@mui/material/Fade";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";

export default function Home() {
  const [open, setOpen] = React.useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  return (
    <motion.div
      initial="hidden"
      animate="visible"
      variants={{
        hidden: {
          opacity: 0,
        },
        visible: {
          opacity: 1,
          transition: {
            delay: 0.7,
          },
        },
      }}
      className={styles.container}
    >
      <Head>
        <title>Rhoda-Phillips-Osei | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <div className={styles.homecontents}>
        <Grid container spacing={2} className={styles.textimage}>
          <Grid lg={3.5} className={styles.leftsidehome}>
            <Item>
              <div className={styles.leftcontents}>
               <div className={styles.textcontrol}>
                <div>
                  <h1>Hi!</h1>
                  My name is <b>Rhoda Phillips-Osei</b>, and I am a 
                   <b> Junior Full Stack Developer</b> from <b>Toronto, Canada</b>.
                  <br></br>
                  <br></br>
                  {/* <br></br> */}
                  <div className={styles.btnrow}>
                    <div className={styles.homebtns}>
                      <Button className={styles.homebtn} onClick={handleOpen}>
                        <a>PROJECTS</a>
                      </Button>
                      <Modal
                        aria-labelledby="transition-modal-title"
                        aria-describedby="transition-modal-description"
                        open={open}
                        onClose={handleClose}
                        closeAfterTransition
                        BackdropComponent={Backdrop}
                        BackdropProps={{
                          timeout: 500,
                        }}
                      >
                        <Fade in={open}>
                          <Box sx={style}>
                            <Typography
                              id="transition-modal-title"
                              variant="h6"
                              component="h2"
                            >
                              <p>
                                <h1>Projects</h1>
                              </p>
                            </Typography>
                            <Typography
                              id="transition-modal-description"
                              sx={{ mt: 2 }}
                            >
                              Duis mollis, est non commodo luctus, nisi erat
                              porttitor ligula.
                            </Typography>
                          </Box>
                        </Fade>
                      </Modal>
                      <Button className={styles.homebtn}>
                        <a>ABOUT ME</a>
                      </Button>
                    </div>
                  </div>
                </div>
                </div>
              </div>
            </Item>
          </Grid>
          <Grid item lg={3.5} className={styles.rightsidehome}>
            <Item>
              <div className={styles.rightcontents}>
                <div class={styles.imgcontainer}>
                  <Image
                    src="/01.webp"
                    alt="Rhoda Phillips-Osei"
                    className={styles.homeimg}
                    width="100%"
                    height="100%"
                    layout="responsive"
                    objectFit="contain"
                  ></Image>
                </div>
              </div>
            </Item>
          </Grid>
        </Grid>
      </div>
    </motion.div>
  );
}

const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 1200,
  height: "800px",
  bgcolor: "background.paper",
  border: "2px solid #ffff",
  borderRadius: "10px",
  boxShadow: 23,
  p: 4,
};

// const navStyle = {
//  background-color: rgba(255, 255, 255, 0.1);
// }
