import Head from "next/head";
import Image from "next/image";
import Breadcrumbs from "@mui/material/Breadcrumbs";
import Link from "@mui/material/Link";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav.";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rhoda-Phillips-Osei | Web Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      </div>
  );
}
