import React from 'react'
import Head from "next/head";
import Image from "next/image";
import Breadcrumbs from "@mui/material/Breadcrumbs";
import Link from "@mui/material/Link";
import styles from "../styles/Home.module.css";
import Nav from "../components/Nav.";
import { motion } from "framer-motion";
import Grid from "@mui/material/Grid";
import Item from "@mui/material/Box";
import Button from "@mui/material/Button"


export default function Home() {
  const [open, setOpen] = React.useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  return (
    <motion.div
      initial="hidden"
      animate="visible"
      variants={{
        hidden: {
          opacity: 0,
        },
        visible: {
          opacity: 1,
          transition: {
            delay: 0.7,
          },
        },
      }}
      className={styles.container}
    >
       <Head>
        <title>Rhoda-Phillips-Osei | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <div className={styles.homecontents}>
        <Grid container spacing={2}>
          <Grid lg={4} className={styles.leftsidehome}>
          <Item>
              <div className={styles.leftcontents}>
                <div class={styles.imgcontainer}>
                  <Image
                    src="/01.webp"
                    alt="Rhoda Phillips-Osei"
                    className={styles.homeimg}
                    width="100%"
                    height="100%"
                    layout="responsive"
                    objectFit="contain"
                  ></Image>
                </div>
              </div>
            </Item>
          
          </Grid>
          <Grid item lg={8} className={styles.rightsidehome}>
          <Item>
              <div className={styles.rightcontents}>
                <p>
                  <h1>Hi!</h1>
                  My name is <b>Rhoda Phillips-Osei</b>, and I am a <b>Junior Full Stack Developer</b> from
                  Toronto, Canada.<br></br><br></br>
                  <div className={styles.btnrow}>
                  <div className={styles.homebtns}>
                  <Button className={styles.homebtn} onClick={handleOpen}><a>PROJECTS</a></Button>
                  <Button className={styles.homebtn}><a>ABOUT ME</a></Button>
                </div>
                </div>
                </p>
              </div>
            </Item>
            
          </Grid>
        </Grid>
      </div>
    </motion.div>
  );
}
